**Python Basic Terms**

*   Syntax (Valid & Invalid)
*   Comments

In [2]:
address = 'Pimpri Chinchwad, Pune : 411057'    # This is my address
print(address)                                # This is the print statement

Pimpri Chinchwad, Pune : 411057


In [4]:
print('Pune')

Pune


In [6]:
address

'Pimpri Chinchwad, Pune : 411057'

**Python Data Types, Type Casting & Variables**

*   **Text Type:**	str
*   **Numeric Types:**	int, float
*   **Sequence Types:**	list, tuple, range
*   **Mapping Type:**	dict
*   **Set Types:**	set
*   **Boolean Type:**	bool

In [9]:
name = 'Ajin'
age = 20
height = 5.8

profile_1= ['Ajin',25,5.8,60,'Engineer']         # List Method
profile_2 = ('Mssi',23,5.5,55,'Teacher')        # Tuple Method
profile_3 = {'Name':'Sai','Role':'Cricket Analyst','age':22,'City':'Pune'} # Dictionary Method
profile_4 = {'Sreedevi',55.6,'Teacher', 5.6}     # Set Method

In [11]:
print(profile_4)

{'Teacher', 5.6, 'Sreedevi', 55.6}


In [13]:
type(profile_4)

set

In [15]:
type(profile_3)

dict

In [17]:
type(profile_2)

tuple

In [19]:
type(profile_1)

list

**Python Operators**

*   Arithmetic operators
*   Assignment operators
*   Comparison operators
*   Logical operators
*   Membership operators

In [34]:
# Arithmetic Operators (+,-,*,/,%,**)                        # Used with numeric values to perform common mathematical operations

x = 3
y = 4

# print(x+y, x-y, x*y, x/y, x%y, x**y)

print(x*y)

12


In [38]:
# Assignment Operators (=,+=,-=,*=,/=,%=,**=)                # Used to assign values to variables

x, y = 7, 3

# x = x - y
# x -= y 
# x = x - y/

x = x * y
print(x)

21


In [40]:
# Comparison Operators (==,!=,<,>,<=,>=)                     # Used to compare two values
# print(x == y, x != y, x < y, x > y, x <= y, x >= y)

x, y = 5, 8
x >= y

False

In [42]:
# Logical Operators (==,!=,<,>,<=,>=)                        # Used to combine conditional statements
# print(x and y)

case1 =(x < y) or (x == y)
print(case1,not(case1))

True False


In [44]:
# Membership Operators (==,!=,<,>,<=,>=)                     # Used to test if a sequence is presented in an object
# print(x in y, x not in y)

x = [1,2,3,4,5]
y = 6

y not in x

True


# List and it's Methods

Lists are used to store multiple items in a single variable.

*   Lists are used to store multiple items in a single variable.
*   It is a collection which is ordered, changeable and allows duplicate members.

**List Methods**


append(), sort(), reverse(), remove(), pop(), insert(), index(), extend(), count(), copy(), clear()

In [49]:
fruits = ['apple', 'cherry', 'banana']
fruits.append("orange")
fruits

['apple', 'cherry', 'banana', 'orange']

In [51]:
fruits = ['apple', 'cherry', 'banana']
fruits.sort()
fruits

['apple', 'banana', 'cherry']

In [53]:
fruits = ['apple', 'cherry', 'banana']
fruits.reverse()
fruits

['banana', 'cherry', 'apple']

In [55]:
fruits = ['apple', 'cherry', 'banana']
fruits.remove('banana')
fruits

['apple', 'cherry']

In [57]:
fruits = ['apple', 'cherry', 'banana']
fruits.pop(1)
fruits

['apple', 'banana']

In [59]:
fruits = ['apple', 'cherry', 'banana']
fruits.insert(1, "watermelon")
fruits

['apple', 'watermelon', 'cherry', 'banana']

In [63]:
fruits = ['apple', 'cherry', 'banana']
fruits.index("cherry")
fruits

['apple', 'cherry', 'banana']

In [67]:
fruits = ['apple', 'cherry', 'banana']
fruits2 = ['pineapple', 'strawaberry', 'guava','cherry','pineapple']
fruits.extend(fruits2)
fruits

['apple',
 'cherry',
 'banana',
 'pineapple',
 'strawaberry',
 'guava',
 'cherry',
 'pineapple']

In [69]:
fruits.count("cherry")
fruits

['apple',
 'cherry',
 'banana',
 'pineapple',
 'strawaberry',
 'guava',
 'cherry',
 'pineapple']

In [73]:
fruits.copy()
fruits

In [75]:
fruits.clear()
fruits

[]

# String and it's Methods

*   All string methods returns new values. They do not change the original string.

**String Methods**

*   isalpha(), isalnum(), index(), find(), count(), capitalize(), isdigit(), islower(), isnumeric()
*   endswith(), upper(), title(), swapcase(), strip(), startswith(), split(), join(), lower(), replace()

In [80]:
txt = "hello, my name is Ajin."
a = txt.capitalize()
print(a)

Hello, my name is ajin.


In [82]:
txt = "I am from India and born in Kerala, India"
b = txt.count("India")
print(b)

2


In [84]:
txt = "I love movies"
c = txt.find("movies")
print(c)

7


In [86]:
d = txt.index("movies")
print(d)

7


In [88]:
txt = "hello, my name is Ajin, I am 20 years old"
e = txt.split(',')
print(e)

['hello', ' my name is Ajin', ' I am 20 years old']


## Methods

In [91]:
txt = "messi10"
name = txt.isalnum()
print(name)

True


In [93]:
txt = "messi"
alpha = txt.isalpha()
print(alpha)

True


In [95]:
txt = '800'
num = txt.isdigit()
print(num)

True


In [97]:
names = ["Messi", "luna", "Hume"]
joined = "_".join(names)
print(joined)

Messi_luna_Hume


In [101]:
txt = "I love Football"
result = txt.replace("Football", "Sports")
print(result)

I love Sports


# Python Conditional Statements

*   If , elif, else statements

In [108]:
a = 33
b = 200
if b > a:
  print("Entered")
else:
  print('Did not entered')

Entered


In [118]:
Thor = 80 
Hulk = 80

if Thor > Hulk:
  print("Thor is greater than Hulk")
elif Thor == Hulk:
  print("Both are equal")
else:
  print("Hulk is greater than Thor")

Both are equal


In [124]:
marks = 72

if marks > 35:
  print("He is Pass")
  if marks > 60:
    print("He got Distinction")
  else:
    print("He is in Mid Range")
else:
  print('He is Failed')

He is Pass
He got Distinction


# For Loop

*   It is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).
*   Using Break & Contiue keyword

In [127]:
fruits = ["apple", "banana", "cherry",'pineappple','mango']

for i in fruits:
  print(i)

apple
banana
cherry
pineappple
mango


## Break

In [130]:
for x in fruits:
  print(x)
  if x == "banana":
    break

apple
banana


## Countinue

In [133]:
for x in fruits:
  if x == "cherry":
    continue
  print(x)

apple
banana
pineappple
mango


# While Loop

*   With the while loop we can execute a set of statements as long as a condition is true.
*   Using Break & Contiue keyword

In [136]:
num = 1

while num < 6:
  print(num)
  num += 1

1
2
3
4
5


In [138]:
num = 1

while num < 6:
  print(num)
  if num == 3:
    break
  num = num + 1

1
2
3


In [140]:
num = 0

while num < 10:
  num += 1
  if num == 5:
    continue
  print(num)

1
2
3
4
6
7
8
9
10


# Python Functions

*   A function is a block of code which only runs when it is called.
*   Advanced Functions - lambda, map, zip

In [148]:
def intro():                     # Function Defining
  value = 5
  return value**2

In [150]:
intro()

25

In [160]:
def my_ID(name):                    # Function with Arguments
  print("LM010_" + name)

In [162]:
my_ID("Messi")

LM010_Messi


In [164]:
# Using Lambda Function

add = lambda a,b,c: print(a+b+c)

In [166]:
add(5,5,6)

16


In [168]:
# Map Function

nums = [1, 2, 3, 4, 5]

def sq(n):
    return n*n

# sq(2)

square = map(sq, nums)

print(list(square))

[1, 4, 9, 16, 25]


In [172]:
# Zip Function

name = ["LS", "Njr", "LM"]
ID = [4, 1, 3]

mapped = zip(name, ID)

print(list(mapped))

[('LS', 4), ('Njr', 1), ('LM', 3)]


# Tuple
They are used to store multiple items in a single variable.
A tuple is a collection which is ordered and unchangeable.
It is written with round brackets.

In [175]:
fruits = ("apple", "banana", "cherry")                           # Standard Method
print(fruits)

('apple', 'banana', 'cherry')


In [177]:
fruits = ("apple", "banana", "cherry","banana")                  # Allows Duplicates
print(fruits)

('apple', 'banana', 'cherry', 'banana')


In [179]:
# Count() Method

nums = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)
nums.count(6)

1

In [181]:
# Index() Method

nums = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)
nums.index(5)

5

In [185]:
# Min() & Max() Method

nums = (1, 3, 7, 99, 7, 5, 4, 6, 8, 5)
min(nums)

1

In [187]:
max(nums)

99

# Dictionary
Dictionaries are used to store data values in key:value pairs.

A dictionary is a collection which is ordered*, changeable and do not allow duplicates.

In [212]:
car = {"brand": "Ford","model": "Mustang","year": 1964}
# Get() Method
car.get("year")

1964

In [214]:
car

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [196]:
# items() Method
car.items()

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])

In [198]:
 # key() Method
car.keys()

dict_keys(['brand', 'model', 'year'])

In [200]:
# values() Method
car.values()

dict_values(['Ford', 'Mustang', 1964])

In [202]:
# pop() Method
# car
car.pop("year")
print(car)

{'brand': 'Ford', 'model': 'Mustang'}


In [204]:
# popitem() Method
car.popitem()
print(car)

{'brand': 'Ford'}


In [206]:
# update() Method

car.update({"color": "White"})
print(car)

{'brand': 'Ford', 'color': 'White'}


In [216]:
# clear() Method

car.clear()
print(car)

{}


# Set
Sets are used to store multiple items in a single variable.

Sets are written with curly brackets.

In [221]:
fruits = {"apple", "banana", "cherry"}

In [223]:
fruits.add("orange")
print(fruits)

{'orange', 'cherry', 'apple', 'banana'}


In [225]:
fruits.pop()
print(fruits)

{'cherry', 'apple', 'banana'}


In [227]:
fruits.remove("cherry")
print(fruits)

{'apple', 'banana'}


In [229]:
type(fruits)

set

In [231]:
fruits = {"apple", "banana", "cherry"}
company = {"google", "microsoft", "apple"}

# difference()

print(company.difference(fruits))       # Output will be from LHS of dot set only

{'microsoft', 'google'}


In [233]:
# intersection()

print(company.intersection(fruits))      # Print common element from both the sets

{'apple'}


In [235]:
# union()

print(company.union(fruits))        # Combine both sets together to form new set

{'cherry', 'microsoft', 'apple', 'google', 'banana'}


# Numpy Array Dimensions

1D Array

2D Array

3D Array

In [238]:
import numpy as np     # importing numpy library

In [240]:
A = np.array(5)        # Scalar Array
A

array(5)

In [244]:
np.ndim(A)               # Dimension method

0

In [246]:
One = np.array([1, 2, 3, 4, 5])
Two = np.array([[1, 2, 3], [4, 5, 6]])
Three = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]]])

In [248]:
Three

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [250]:
Three.shape
np.ndim(Three)

3

In [252]:
np.ndim(One)
np.ndim(Two)
np.ndim(Three)

3

# List vs Numpy Array

In [255]:
list1 = [1,4.0,'apple']                     # List - Different Datatypes
arr = np.array([1, 2, 3, 4, 5])             # Array - Similar Datatypes

In [257]:
arr

array([1, 2, 3, 4, 5])

In [259]:
arr = np.array([1, 2, 3.9, 'apple'])        # Type Conversion

In [261]:
arr

array(['1', '2', '3.9', 'apple'], dtype='<U32')

# More Advantages of Numpy Array over list

*   Array consumes less memory
*   Array are faster than lists

# Reshaping arrays

Reshaping means changing the shape of an array.

In [269]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   # 1D Array

# 1D to 2D Array
newarr = arr.reshape(3, 4)


In [271]:
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [277]:
# 1D to 3D Array

newarr = arr.reshape(2, 3, 2)    # x,y,z: x = matrix, y = rows, z = cols

In [279]:
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Array Indexing

Array indexing is the same as accessing an array element.
You can access an array element by referring to its index number.

In [282]:
arr = np.array([1, 2, 3, 4])              # Accessing 1D Array

print(arr[3])

4


In [284]:
print(arr[0] + arr[1])                 # Addition of 2 elements

3


In [286]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  # Accessing 2D Array
arr.shape

# print(arr[0, 3])                          # 1st row 4th element
# print(arr[1, 1])                          # 2nd row 5th element
print(arr[1,3])

9


In [288]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [290]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   # Accessing 3D Array

arr3.shape
# print(arr3)
# print(arr3[0, 0, 2])               # 1st matrix, 1st row, 3rd column
# print(arr3[1, 1, 1])               # 1st matrix, 2nd row, 1st column
print(arr3[0,1,0])

4


In [292]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [295]:
import numpy as np

a1 = np.array([1, 2, 3, 4, 5, 6, 7])             # Slicing 1D Array

print(a1[1:5])     # Slicing                                  # [start:end]
print(a1[4])     # Indexing
a1[:4]

[2 3 4 5]
5


array([1, 2, 3, 4])

In [297]:
a2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])      # Slicing 2D Array

a2[1, 1:4]                                            # [row:column]
a2[0:2, 2]
# a2[1:, :5]

array([3, 8])

In [299]:
a2.shape

(2, 5)

In [301]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])           # # Slicing 3D Array

In [303]:
a3[:2,1:,:]

array([[[13, 14, 15],
        [16, 17, 18]],

       [[23, 24, 25],
        [26, 27, 28]]])

# View vs Copy

Copy is a new array, and the View is just a view of the original array.

Any changes made to the **copy** will not affect original array.

Any changes made to the **view** will affect the original array.

In [306]:
arr = np.array([1, 2, 3, 4, 5])

# Copy Method

copy = arr.copy()
copy[0] = 42

print(arr)
print(copy)

[1 2 3 4 5]
[42  2  3  4  5]


In [308]:
# View Method

view = arr.view()
view[0] = 42

print(arr)
print(view)

[42  2  3  4  5]
[42  2  3  4  5]


# Append , Insert and Delete Operations

In [311]:
a = np.array([[1,2,3],
              [4,5,6]])
a.shape
# Append Method

np.append(a, [7,8,9])
np.append(a, [[7,8,9]],axis = 0)                # axis = 0 = row , axis = 1 = col
np.append(a, [[5],[8]],axis = 1)

array([[1, 2, 3, 5],
       [4, 5, 6, 8]])

In [313]:
a = np.array([[1,2],
              [3,4],
              [5,6]])

# Insert Method

np.insert(a,3,[11,12])
np.insert(a,1,[11,12],axis = 0)
# np.insert(a,1,[11,12,13],axis = 1)

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [315]:
a = np.array([[ 1,  2,  3, 12],
              [ 9,  5,  6,  11],
              [ 8,  4, 10, 7]])

# Delete Method

# np.delete(a,4)
# np.delete(a,1,axis = 1)
np.delete(a,1,axis = 0)

array([[ 1,  2,  3, 12],
       [ 8,  4, 10,  7]])

In [317]:
np.ndim(a)

2

# Hstack vs Vstack

Hstack is used to join two arrays **Horizontally**.

Vstack is used to join two arrays **Vertically**.

In [326]:
import numpy as np

In [332]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [334]:
print(a,b)
print(np.ndim(a), np.ndim(b))

[1 2 3] [4 5 6]
1 1


In [336]:
# Performing Hstack

result = np.hstack((a,b))

print(result)
print(np.ndim(result))

[1 2 3 4 5 6]
1


In [338]:
# Performing Vstack

result = np.vstack((a,b))
print(result, np.ndim(result))

[[1 2 3]
 [4 5 6]] 2


# Numpy Concatenation

It is used for joining two or more arrays of the same shape along a specified axis.

Axis = 0, Adding new rows

Axis = 1, Adding new columns

In [343]:
arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([[3, 5], [7, 9]])

# print(arr1.shape,arr2.shape)

arr3 = np.array([[3], [9]])
arr4 = np.array([[4] , [8]])

print(arr3.shape,arr4.shape)

new = np.concatenate((arr1, arr2), axis = 0)

#print(new, new.shape)

(2, 1) (2, 1)


In [345]:
new = np.concatenate((arr3, arr4), axis = 1)

print(new)

[[3 4]
 [9 8]]


# Pandas Series

A Pandas Series is like a column in a table.
It is a one-dimensional array holding data of any type.

In [348]:
import pandas as pd

In [350]:
# Series Method

series = pd.Series([1, 7, 2, 8, 5])

print(series)

0    1
1    7
2    2
3    8
4    5
dtype: int64


In [352]:
# Series Method with Index

series = pd.Series([1, 7, 2, 8, 5], index = ["a", "b", "c","d","e"])

print(series)

a    1
b    7
c    2
d    8
e    5
dtype: int64


In [356]:
# Accessing Series elements

print(series[2])
print(series["c"])

2
2


C:\Users\ajint\AppData\Local\Temp\ipykernel_3152\4006098312.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series[2])


# Pandas DataFrame

A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns.

In [359]:
# DataFrame Method on list

data = pd.DataFrame([1,2,3,4,5])
print(data)

   0
0  1
1  2
2  3
3  4
4  5


In [361]:
# DataFrame using Dictionary

data = pd.DataFrame({'Name':['Tom', 'Jack', 'Steve', 'Ricky','Sam','Will','Root'],
                     'Age':[28,34,29,42,17,17,45]})
data.head(10)

Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42
4    Sam   17
5   Will   17
6   Root   45

In [ ]:
# data.head(5)

In [363]:
# DataFrame with Index

data = pd.DataFrame({'Name':['Tom', 'Jack', 'Steve', 'Ricky','Sam','Will','Root'],
                     'Age':[28,34,29,42,17,17,45]}, index=['C1','C2','C3','C4','C5','C6','C7'])
data.head(10)

Name  Age
C1    Tom   28
C2   Jack   34
C3  Steve   29
C4  Ricky   42
C5    Sam   17
C6   Will   17
C7   Root   45

In [365]:
# Column Selection

# data['Name']
data['Age']

C1    28
C2    34
C3    29
C4    42
C5    17
C6    17
C7    45
Name: Age, dtype: int64

In [367]:
data.head(10)

Name  Age
C1    Tom   28
C2   Jack   34
C3  Steve   29
C4  Ricky   42
C5    Sam   17
C6   Will   17
C7   Root   45

In [369]:
# Row Selection

# data.loc['C4','Age']
data.iloc[3,0]

'Ricky'

# Pandas Concatenation

It is used to concatenate pandas objects along a particular axis with optional set logic along the other axes.

In [372]:
names = pd.DataFrame({'Name':['Tom', 'Jack', 'Steve', 'Ricky','Sam','Will','Root']})
ages = pd.DataFrame({'Age':[28,34,29,42,17,17,45]})

In [374]:
names2 = pd.DataFrame({'Name':['Joe', 'Pope', 'Buttler', 'Ben','James','Cook']})

In [376]:
names2

Name
0      Joe
1     Pope
2  Buttler
3      Ben
4    James
5     Cook

In [378]:
ages

Age
0   28
1   34
2   29
3   42
4   17
5   17
6   45

In [380]:
pd.concat([names, ages], axis = 1)                     # Concatenation

Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42
4    Sam   17
5   Will   17
6   Root   45

In [382]:
pd.concat([names, names2])                # Concatenation

Name
0      Tom
1     Jack
2    Steve
3    Ricky
4      Sam
5     Will
6     Root
0      Joe
1     Pope
2  Buttler
3      Ben
4    James
5     Cook

# Pandas Indexing

loc() , iloc(), Filtering methods

In [388]:
data

Name  Age
C1    Tom   28
C2   Jack   34
C3  Steve   29
C4  Ricky   42
C5    Sam   17
C6   Will   17
C7   Root   45

In [390]:
# data['Name']
data[['Name','Age']]

Name  Age
C1    Tom   28
C2   Jack   34
C3  Steve   29
C4  Ricky   42
C5    Sam   17
C6   Will   17
C7   Root   45

In [392]:
data[data['Age'] <= 18][['Name']]

Name
C5   Sam
C6  Will

In [394]:
data[data['Age'] > 40]

Name  Age
C4  Ricky   42
C7   Root   45

In [396]:
print(data.loc['C2','Name'])
print(data.iloc[1,0])

Jack
Jack


# Pandas Creating & Reading CSV files

In [399]:
import pandas as pd

In [401]:
data = pd.DataFrame({
    'Name' : ['Ankit', 'Aishwarya', 'Sanket', 'Shivangi', 'Saiprasad', 'Rishika', 'Pratiksha'],
    'Age' : [23, 21, 22, 21, 22, 21, 20],
    'University' : ['BHU', 'JNU', 'DU', 'BHU', 'SPPU', 'SPPU', 'DU'],
})

In [403]:
data

Name  Age University
0      Ankit   23        BHU
1  Aishwarya   21        JNU
2     Sanket   22         DU
3   Shivangi   21        BHU
4  Saiprasad   22       SPPU
5    Rishika   21       SPPU
6  Pratiksha   20         DU

In [405]:
# data.to_csv('students.csv')
data.to_csv('students.csv', index = False)

# Uploading Datasets

In [410]:
#students = pd.read_csv('/content/students.csv')

In [414]:
#students

# Groupby Function

In [419]:
#emp = pd.read_csv('/content/Employees.csv')

In [ ]:
grouped = emp.groupby('Department')

tech = grouped.get_group('Technical')
market = grouped.get_group('Marketing')
admin = grouped.get_group('Administration')

In [ ]:
market['Years of Experience'].mean()

# Top Commands

Creating New, Renaming & Droping Columns.

Apply Method, Sort Index, Sort Values.

In [424]:
data

Name  Age University
0      Ankit   23        BHU
1  Aishwarya   21        JNU
2     Sanket   22         DU
3   Shivangi   21        BHU
4  Saiprasad   22       SPPU
5    Rishika   21       SPPU
6  Pratiksha   20         DU

In [426]:
# Creating New Columns

data['City'] = ['Delhi', 'Bangalore', 'Chennai', 'Patna', 'Pune', 'Pune', 'Mumbai']

In [430]:
data

Name  Age University       City
0      Ankit   23        BHU      Delhi
1  Aishwarya   21        JNU  Bangalore
2     Sanket   22         DU    Chennai
3   Shivangi   21        BHU      Patna
4  Saiprasad   22       SPPU       Pune
5    Rishika   21       SPPU       Pune
6  Pratiksha   20         DU     Mumbai

In [432]:
#remaining columns
data.columns = ['First Name','Current Age','College University','Location']

In [434]:
data

First Name  Current Age College University   Location
0      Ankit           23                BHU      Delhi
1  Aishwarya           21                JNU  Bangalore
2     Sanket           22                 DU    Chennai
3   Shivangi           21                BHU      Patna
4  Saiprasad           22               SPPU       Pune
5    Rishika           21               SPPU       Pune
6  Pratiksha           20                 DU     Mumbai

In [436]:
data.drop(['Current Age'], axis = 1)           # Temporary Droping Syntax

First Name College University   Location
0      Ankit                BHU      Delhi
1  Aishwarya                JNU  Bangalore
2     Sanket                 DU    Chennai
3   Shivangi                BHU      Patna
4  Saiprasad               SPPU       Pune
5    Rishika               SPPU       Pune
6  Pratiksha                 DU     Mumbai

In [438]:
data.drop(['Current Age'], axis = 1, inplace = True)           # Permanent Droping Syntax

In [440]:
# Creating Marks Column

data['Marks'] = [201, 210, 195, 183, 225, 203, 190]

In [442]:
# Apply Method

data['Marks'] = data['Marks'].apply(lambda x: x/5)

In [444]:
# Renaming Column

data.columns = ['First Name','College University','Location', 'Marks/Subject']

In [446]:
data.index = [10,28,64,7,1,6,15]          # Assigning Index

In [448]:
data.sort_index(ascending = True)                      # Default Statement : Ascending = True

First Name College University   Location  Marks/Subject
1   Saiprasad               SPPU       Pune           45.0
6     Rishika               SPPU       Pune           40.6
7    Shivangi                BHU      Patna           36.6
10      Ankit                BHU      Delhi           40.2
15  Pratiksha                 DU     Mumbai           38.0
28  Aishwarya                JNU  Bangalore           42.0
64     Sanket                 DU    Chennai           39.0

In [450]:
data.sort_index(ascending = False)                      # Default Statement : Ascending = True

First Name College University   Location  Marks/Subject
64     Sanket                 DU    Chennai           39.0
28  Aishwarya                JNU  Bangalore           42.0
15  Pratiksha                 DU     Mumbai           38.0
10      Ankit                BHU      Delhi           40.2
7    Shivangi                BHU      Patna           36.6
6     Rishika               SPPU       Pune           40.6
1   Saiprasad               SPPU       Pune           45.0

In [452]:
data.sort_values(by = 'Marks/Subject', ascending = False)   #sort values

First Name College University   Location  Marks/Subject
1   Saiprasad               SPPU       Pune           45.0
28  Aishwarya                JNU  Bangalore           42.0
6     Rishika               SPPU       Pune           40.6
10      Ankit                BHU      Delhi           40.2
64     Sanket                 DU    Chennai           39.0
15  Pratiksha                 DU     Mumbai           38.0
7    Shivangi                BHU      Patna           36.6